name: Deploy MWS Serverless Auth

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 📦 Instalar Dependências
        run: npm install

      - name: 🤐 Empacotar (Zip)
        run: zip -r deployment.zip index.js node_modules/ package.json

      - name: ☁️ Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: 🚀 Deploy do Código na AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name mws-auth-lambda \
            --zip-file fileb://deployment.zip
          
      - name: ⏳ Aguardar AWS processar o código
        run: |
          aws lambda wait function-updated \
            --function-name mws-auth-lambda

      - name: ⚙️ Atualizar Variáveis de Ambiente
        env:
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_DATABASE: ${{ secrets.DB_DATABASE }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
            aws lambda update-function-configuration \
              --function-name mws-auth-lambda \
              --environment "{\"Variables\":{\"DB_HOST\":\"$DB_HOST\",\"DB_USER\":\"$DB_USER\",\"DB_PASSWORD\":\"$DB_PASSWORD\",\"DB_DATABASE\":\"$DB_DATABASE\",\"JWT_SECRET\":\"$JWT_SECRET\"}}"